name: StormtrooperX
version: '${project.version}'
main: com.goobercraft.stormtrooperx.StormtrooperX
api-version: '1.13'
author: GooberCraft
description: A plugin that nerfs the accuracy of ranged mobs like Skeletons, Strays, Bogged, Pillagers, and Piglins
website: https://github.com/GooberCraft/StormtrooperX

commands:
  stormtrooperx:
    description: Main command for StormtrooperX
    usage: /stormtrooperx <reload|optout>
    aliases: [stx, stormtrooper]
    permission: stormtrooperx.use

permissions:
  stormtrooperx.use:
    description: Allows access to the main command
    default: op
  stormtrooperx.reload:
    description: Allows reloading the plugin configuration
    default: op
  stormtrooperx.optout:
    description: Allows players to opt-out of mob accuracy nerfs
    default: true
