name: Bug Report
description: Report a bug or issue with StormtrooperX
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix the issue.

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of StormtrooperX are you using?
      placeholder: e.g., 1.2.0
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What Minecraft version is your server running?
      placeholder: e.g., 1.20.1
    validations:
      required: true

  - type: input
    id: server-software
    attributes:
      label: Server Software
      description: What server software are you using?
      placeholder: e.g., Paper 1.20.1, Spigot 1.19.4, Purpur 1.20.1
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: What Java version is your server running?
      placeholder: e.g., Java 17, Java 21
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what's happening...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Configure plugin with...
        2. Spawn a skeleton...
        3. Notice that...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The mob should...

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, the mob...

  - type: textarea
    id: logs
    attributes:
      label: Logs and Errors
      description: |
        Paste any relevant error messages or logs here.
        Enable debug mode in config.yml for more detailed logs.
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your config.yml contents (optional but helpful)
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be relevant (screenshots, other plugins, etc.)
