name: Feature Request
description: Suggest a new feature or enhancement for StormtrooperX
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like the plugin to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.

  - type: dropdown
    id: willing-to-help
    attributes:
      label: Would you be willing to help implement this?
      options:
        - "Yes, I can submit a pull request"
        - "Yes, I can help test it"
        - "No, but I can provide feedback"
        - "Not sure"
    validations:
      required: false
