name: Question
description: Ask a question about StormtrooperX
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using StormtrooperX? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Provide any relevant context that might help us answer your question.
        Include your setup details if applicable (Minecraft version, server software, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Before asking
      description: Please confirm you've done the following
      options:
        - label: I've read the [README](https://github.com/mdw19873/StormtrooperX/blob/master/README.md)
        - label: I've checked existing [issues](https://github.com/mdw19873/StormtrooperX/issues) for similar questions
