name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 17, 21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Run tests
      run: mvn clean test

    - name: Publish test results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: target/surefire-reports/TEST-*.xml

    - name: Upload coverage reports
      if: matrix.java-version == 8
      uses: codecov/codecov-action@v4
      with:
        files: target/site/jacoco/jacoco.xml
        fail_ci_if_error: false

    - name: Build with Maven
      run: mvn package -DskipTests

    - name: Get version from pom.xml
      id: get_version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

    - name: Upload artifact
      if: matrix.java-version == 8
      uses: actions/upload-artifact@v4
      with:
        name: StormtrooperX-${{ steps.get_version.outputs.VERSION }}
        path: target/StormtrooperX-*.jar
        if-no-files-found: error
